site_name: ypy-websocket-zh-cn
site_description: Ypy的异步 WebSocket 链接器
repo_url: https://github.com/hellowac/ypy-websocket-zh-cn

theme:
  name: "material"
  palette:
    - scheme: default
      primary: "blue"
      accent: "red"
      toggle:
        icon: material/lightbulb-outline
        name: 切换到夜间模式
    - scheme: slate
      primary: "black"
      accent: "black"
      toggle:
        icon: material/lightbulb
        name: 切换到白天模式
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy

nav:
  - 概览: index.md
  - install.md
  - 用法:
      - usage/client.md
      - usage/server.md
      - usage/WebSocket_API.md
  - 代码参考:
      - reference/WebSocket_provider.md
      - reference/WebSocket_server.md
      - reference/ASGI_server.md
      - reference/Django_Channels_consumer.md
      - reference/WebSocket.md
      - reference/Room.md
      - reference/Store.md

markdown_extensions:
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - mkdocstrings:
      default_handler: python
